# Welcome to Jekyll!
#
encoding: utf-8
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: JC
email: jacopo.canton@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
    These are Jacopo's pages on GitHub
twitter_username: JacopoCanton
github_username: jcanton
minimal_mistakes_skin: air
search: true

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name   : "Jacopo Canton"
  avatar : "/assets/images/bio-photo.png"
  bio    : "My awesome biography on my personal pages."
  links:
      #- label: "Website"
      #  icon: "fas fa-fw fa-link"
      #  url: "https://jcanton.github.io/"
      #- label: "Twitter"
      #  icon: "fab fa-fw fa-twitter-square"
      #  url: "https://twitter.com/JacopoCanton"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/jcanton"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin-in"
      url: "https://www.linkedin.com/in/jacopo-canton"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://instagram.com/jacopocanton"

footer:
  links:
      #- label: "Twitter"
      #  icon: "fab fa-fw fa-twitter-square"
      #  url: "https://twitter.com/JacopoCanton"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/jcanton"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin-in"
      url: "https://www.linkedin.com/in/jacopo-canton"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://instagram.com/jacopocanton"

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: false

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
